spring.application.name=api-gateway
server.port=8765
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.web.resources.static-locations=classpath:/static/

# Route for frontend static files
spring.cloud.gateway.routes[0].id=frontend-service
spring.cloud.gateway.routes[0].uri=lb://frontend-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/frontend-service/**

# Route for user service API
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/user-service/**

# Route for courses service API
spring.cloud.gateway.routes[2].id=courses-service
spring.cloud.gateway.routes[2].uri=lb://courses-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/courses-service/**